# Generated by Django 2.2 on 2019-04-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('description', models.TextField()),
                ('lat', models.DecimalField(decimal_places=9, max_digits=9)),
                ('long', models.DecimalField(decimal_places=9, max_digits=9)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoJourney.ngo')),
            ],
        ),
    ]
