# Generated by Django 2.2.1 on 2019-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoJourney', '0002_auto_20190503_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='password',
        ),
    ]
