# Generated by Django 2.2.1 on 2019-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerJourney', '0003_auto_20190430_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
    ]
