# Generated by Django 2.2.1 on 2019-05-03 07:06

from django.db import migrations, models
import volunteerJourney.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerJourney', '0004_remove_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=volunteerJourney.models.get_image_path),
        ),
    ]
